"""add fcc_codes table

Revision ID: 0b6626b7d81a
Revises: c117e7299ade
Create Date: 2025-05-04 16:56:26.010542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6626b7d81a'
down_revision: Union[str, None] = 'c117e7299ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcc_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fcc_id', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('battery', sa.String(), nullable=True),
    sa.Column('button', sa.String(), nullable=True),
    sa.Column('chip', sa.String(), nullable=True),
    sa.Column('keyway', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcc_codes')
    # ### end Alembic commands ###
