"""add fcc_models table and link to fcc_codes

Revision ID: 4193b43c8e75
Revises: 83420563228d
Create Date: 2025-05-04 17:41:08.867467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4193b43c8e75'
down_revision: Union[str, None] = '83420563228d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcc_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fcc_code_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fcc_code_id'], ['fcc_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('fcc_codes', 'model')
    op.drop_column('fcc_codes', 'year')
    op.drop_column('fcc_codes', 'make')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcc_codes', sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('fcc_models')
    # ### end Alembic commands ###
