"""add description to fcc_codes

Revision ID: 83420563228d
Revises: 0b6626b7d81a
Create Date: 2025-05-04 17:15:46.630263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83420563228d'
down_revision: Union[str, None] = '0b6626b7d81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcc_codes', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('fcc_codes', 'battery')
    op.drop_column('fcc_codes', 'frequency')
    op.drop_column('fcc_codes', 'button')
    op.drop_column('fcc_codes', 'chip')
    op.drop_column('fcc_codes', 'keyway')
    op.drop_column('fcc_codes', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcc_codes', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('keyway', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('chip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('button', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fcc_codes', sa.Column('battery', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fcc_codes', 'description')
    # ### end Alembic commands ###
