"""Make fcc_id nullable

Revision ID: d9f854851d2a
Revises: 
Create Date: 2025-05-04 14:14:43.500574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f854851d2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_models')
    op.alter_column('keys', 'fcc_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('keys', 'barcode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('keys', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'fcc'::text"))
    op.alter_column('keys', 'make',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('keys', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('keys', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('keys', 'box_slot',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('keys', 'comments',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('known_codes', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('known_codes', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'session_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'session_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('known_codes', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('known_codes', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('keys', 'comments',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('keys', 'box_slot',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('keys', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('keys', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('keys', 'make',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('keys', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'fcc'::text"))
    op.alter_column('keys', 'barcode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('keys', 'fcc_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_table('key_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('make', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], name='key_models_key_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='key_models_pkey')
    )
    # ### end Alembic commands ###
